### ISSUE TITLE
Criação MER

### ISSUE THREAD

**Issue by Draconnato** [Draconnato/formula-flow#3]

**Comment by draconnato** [comment]
![Image](https://github.com/user-attachments/assets/e18e7796-3c29-4e3f-9632-975ef5dc927a)

[FF-MER.pdf](https://github.com/user-attachments/files/17090157/FF-MER.pdf)

BR Modelo - https://app.brmodeloweb.com/#!/publicview/66f02ea84d04f22ccffe7c04
